# Generated by Django 4.0 on 2022-01-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
