# Generated by Django 4.0 on 2022-01-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_rename_user_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
